"""
Linked Lamp — Build Helper Script

Compiles both firmware variants (PCB and NeoPixel) using PlatformIO,
manages Semantic Versioning (Major, Minor, Patch, and Beta releases),
updates C++ headers and website version configuration,
and copies build artifacts into docs/flash/ for browser-based flashing.

Usage:
   python docs/flash/build_template.py
   python docs/flash/build_template.py --no-prompt
   python docs/flash/build_template.py --promote
   python docs/flash/build_template.py --bump patch --beta
"""

import shutil
import os
import sys
import json
import re
import datetime
import argparse
import subprocess

# Ensure UTF-8 output on Windows consoles
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# Paths relative to this script's location
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FLASH_DIR = SCRIPT_DIR  # docs/flash/
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

# PlatformIO framework tools path (varies by OS)
FRAMEWORK_DIR = os.path.join(
    os.path.expanduser("~"),
    ".platformio", "packages", "framework-arduinoespressif32"
)

VERSION_JSON_PATH = os.path.join(FLASH_DIR, "version.json")
VERSION_JS_PATH = os.path.join(FLASH_DIR, "version.js")
PCB_VERSION_H_PATH = os.path.join(REPO_ROOT, "firmware", "pcb", "include", "version.h")
NEO_VERSION_H_PATH = os.path.join(REPO_ROOT, "firmware", "neopixel", "include", "version.h")


def parse_semver(v_str):
    """
    Parses a SemVer string like '1.2.3' or '1.2.4-beta.5'.
    Returns (major, minor, patch, is_beta, beta_num).
    """
    if not v_str:
        return 1, 0, 0, False, 0
    clean = v_str.strip().lstrip("vV")
    m = re.match(r"^(\d+)\.(\d+)\.(\d+)(?:-beta\.(\d+))?$", clean)
    if m:
        major = int(m.group(1))
        minor = int(m.group(2))
        patch = int(m.group(3))
        is_beta = m.group(4) is not None
        beta_num = int(m.group(4)) if is_beta else 0
        return major, minor, patch, is_beta, beta_num
    # Fallback default
    return 1, 0, 0, False, 0


def load_version_info():
    """Loads docs/flash/version.json or creates default if missing."""
    if os.path.isfile(VERSION_JSON_PATH):
        try:
            with open(VERSION_JSON_PATH, "r", encoding="utf-8") as f:
                data = json.load(f)
                return {
                    "stable": data.get("stable", "1.0.0"),
                    "beta": data.get("beta", None),
                    "lastUpdated": data.get("lastUpdated", datetime.datetime.now(datetime.timezone.utc).isoformat())
                }
        except Exception as e:
            print(f"  ⚠ Warning: Could not read {VERSION_JSON_PATH}: {e}")

    return {
        "stable": "1.0.0",
        "beta": None,
        "lastUpdated": datetime.datetime.now(datetime.timezone.utc).isoformat()
    }


def save_version_info(version_info):
    """Saves docs/flash/version.json and docs/flash/version.js."""
    version_info["lastUpdated"] = datetime.datetime.now(datetime.timezone.utc).isoformat()

    # 1. Write docs/flash/version.json
    with open(VERSION_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(version_info, f, indent=2)
    print(f"  ✓ Updated {os.path.relpath(VERSION_JSON_PATH, REPO_ROOT)}")

    # 2. Write docs/flash/version.js for web browser consumption
    js_content = (
        "// Auto-generated by build_template.py — DO NOT EDIT MANUALLY\n"
        f"window.LINKED_LAMP_VERSIONS = {json.dumps(version_info, indent=2)};\n"
    )
    with open(VERSION_JS_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)
    print(f"  ✓ Updated {os.path.relpath(VERSION_JS_PATH, REPO_ROOT)}")


def write_cpp_version_headers(version_str, is_beta, beta_num, major, minor, patch):
    """Generates version.h for both PCB and NeoPixel firmware targets."""
    header_content = (
        "// Auto-generated by build_template.py — DO NOT EDIT MANUALLY\n"
        "#pragma once\n\n"
        f"#define FIRMWARE_VERSION_MAJOR {major}\n"
        f"#define FIRMWARE_VERSION_MINOR {minor}\n"
        f"#define FIRMWARE_VERSION_PATCH {patch}\n"
        f'#define FIRMWARE_VERSION_STR   "{version_str}"\n'
        f"#define FIRMWARE_IS_BETA       {'true' if is_beta else 'false'}\n"
        f"#define FIRMWARE_BETA_NUM      {beta_num}\n"
    )

    for h_path in [PCB_VERSION_H_PATH, NEO_VERSION_H_PATH]:
        os.makedirs(os.path.dirname(h_path), exist_ok=True)
        with open(h_path, "w", encoding="utf-8") as f:
            f.write(header_content)
        print(f"  ✓ Updated {os.path.relpath(h_path, REPO_ROOT)}")


def bump_version_tuple(major, minor, patch, bump_type):
    """
    Bumps a version tuple based on bump_type.
    Updating a number to the left immediately sets all numbers to the right of it to 0s.
    """
    b = bump_type.lower()
    if b == "major":
        return major + 1, 0, 0
    elif b == "minor":
        return major, minor + 1, 0
    elif b == "patch":
        return major, minor, patch + 1
    return major, minor, patch


def manage_versions_interactive(version_info, args):
    """
    Handles version prompting and updates.
    Returns (updated_version_info, active_build_version, is_beta, beta_num, major, minor, patch).
    """
    current_stable = version_info.get("stable", "1.0.0")
    current_beta = version_info.get("beta", None)

    print("\n" + "=" * 50)
    print("  Linked Lamp Firmware Version Management")
    print("=" * 50)
    print(f"  Current Stable: {current_stable}")
    print(f"  Current Beta:   {current_beta if current_beta else 'None'}")
    print("-" * 50)

    # Check for CLI overrides
    if args.promote:
        if not current_beta:
            print("  ✗ Error: No active beta version to promote.")
            sys.exit(1)
        b_maj, b_min, b_pat, _, _ = parse_semver(current_beta)
        new_stable = f"{b_maj}.{b_min}.{b_pat}"
        print(f"  🚀 Promoting beta {current_beta} -> STABLE {new_stable}")
        version_info["stable"] = new_stable
        version_info["beta"] = None
        return version_info, new_stable, False, 0, b_maj, b_min, b_pat

    if args.no_prompt:
        # Build with current active target (beta if active, otherwise stable)
        if current_beta:
            b_maj, b_min, b_pat, is_b, b_num = parse_semver(current_beta)
            return version_info, current_beta, is_b, b_num, b_maj, b_min, b_pat
        else:
            s_maj, s_min, s_pat, is_b, b_num = parse_semver(current_stable)
            return version_info, current_stable, is_b, b_num, s_maj, s_min, s_pat

    if args.bump:
        # CLI bump
        base_v = current_stable
        b_maj, b_min, b_pat, _, _ = parse_semver(base_v)
        n_maj, n_min, n_pat = bump_version_tuple(b_maj, b_min, b_pat, args.bump)
        if args.beta:
            new_v = f"{n_maj}.{n_min}.{n_pat}-beta.1"
            version_info["beta"] = new_v
            return version_info, new_v, True, 1, n_maj, n_min, n_pat
        else:
            new_v = f"{n_maj}.{n_min}.{n_pat}"
            version_info["stable"] = new_v
            version_info["beta"] = None
            return version_info, new_v, False, 0, n_maj, n_min, n_pat

    # Interactive prompt
    try:
        ans = input("Do you want to update the version number? [y/N]: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print("\nUsing current version.")
        ans = "n"

    if ans != "y":
        print("  Keeping current versions.")
        target_v = current_beta if current_beta else current_stable
        t_maj, t_min, t_pat, is_b, b_num = parse_semver(target_v)
        return version_info, target_v, is_b, b_num, t_maj, t_min, t_pat

    # Ask Release Type
    print("\nSelect Release Type:")
    print("  [1] Stable Release")
    print("  [2] Beta Release")
    rel_choice = input("Enter choice [1 or 2, default: 1]: ").strip()
    is_beta_target = (rel_choice == "2")

    s_maj, s_min, s_pat, _, _ = parse_semver(current_stable)

    if not is_beta_target:
        # STABLE RELEASE
        # If there is an active beta, offer 1-click promotion
        if current_beta:
            b_maj, b_min, b_pat, _, _ = parse_semver(current_beta)
            promoted_v = f"{b_maj}.{b_min}.{b_pat}"
            print(f"\nFound active beta '{current_beta}'.")
            prom = input(f"Promote active beta to STABLE {promoted_v}? [Y/n]: ").strip().lower()
            if prom != "n":
                print(f"  🚀 Promoted to Stable: {promoted_v} (Beta cleared)")
                version_info["stable"] = promoted_v
                version_info["beta"] = None
                return version_info, promoted_v, False, 0, b_maj, b_min, b_pat

        # Otherwise bump from stable
        print(f"\nSelect component to bump from current stable ({current_stable}):")
        print(f"  [1] Major -> {s_maj + 1}.0.0")
        print(f"  [2] Minor -> {s_maj}.{s_min + 1}.0")
        print(f"  [3] Patch -> {s_maj}.{s_min}.{s_pat + 1}")
        bump_choice = input("Enter choice [1/2/3, default: 3]: ").strip()

        if bump_choice == "1":
            n_maj, n_min, n_pat = s_maj + 1, 0, 0
        elif bump_choice == "2":
            n_maj, n_min, n_pat = s_maj, s_min + 1, 0
        else:
            n_maj, n_min, n_pat = s_maj, s_min, s_pat + 1

        new_stable = f"{n_maj}.{n_min}.{n_pat}"
        print(f"  🚀 New Stable: {new_stable} (Beta cleared)")
        version_info["stable"] = new_stable
        version_info["beta"] = None
        return version_info, new_stable, False, 0, n_maj, n_min, n_pat

    else:
        # BETA RELEASE
        # If active beta exists, offer incrementing beta index
        if current_beta:
            b_maj, b_min, b_pat, _, b_num = parse_semver(current_beta)
            next_beta_num = b_num + 1 if b_num > 0 else 2
            next_beta = f"{b_maj}.{b_min}.{b_pat}-beta.{next_beta_num}"
            print(f"\nActive beta is '{current_beta}'.")
            inc = input(f"Increment to next beta '{next_beta}'? [Y/n]: ").strip().lower()
            if inc != "n":
                print(f"  🧪 Updated Beta: {next_beta}")
                version_info["beta"] = next_beta
                return version_info, next_beta, True, next_beta_num, b_maj, b_min, b_pat

        # Otherwise, start new beta from bumped stable
        print(f"\nBump base version for new beta from current stable ({current_stable}):")
        print(f"  [1] Major -> {s_maj + 1}.0.0-beta.1")
        print(f"  [2] Minor -> {s_maj}.{s_min + 1}.0-beta.1")
        print(f"  [3] Patch -> {s_maj}.{s_min}.{s_pat + 1}-beta.1")
        bump_choice = input("Enter choice [1/2/3, default: 3]: ").strip()

        if bump_choice == "1":
            n_maj, n_min, n_pat = s_maj + 1, 0, 0
        elif bump_choice == "2":
            n_maj, n_min, n_pat = s_maj, s_min + 1, 0
        else:
            n_maj, n_min, n_pat = s_maj, s_min, s_pat + 1

        new_beta = f"{n_maj}.{n_min}.{n_pat}-beta.1"
        print(f"  🧪 New Beta: {new_beta} (Stable remains {current_stable})")
        version_info["beta"] = new_beta
        return version_info, new_beta, True, 1, n_maj, n_min, n_pat


def resolve_platformio_cmd():
    """Finds platformio or pio executable across system and user directories."""
    candidates = [
        os.path.join(os.path.expanduser("~"), ".platformio", "penv", "Scripts", "platformio.exe"),
        os.path.join(os.path.expanduser("~"), ".platformio", "penv", "Scripts", "pio.exe"),
        "platformio",
        "pio"
    ]
    for c in candidates:
        if os.path.isfile(c) or shutil.which(c):
            return c
    return "pio"


def compile_firmware(is_beta=False):
    """Compile both PCB and NeoPixel firmware using PlatformIO."""
    pio_cmd = resolve_platformio_cmd()
    hw_types = ["pcb", "neopixel"]

    for hw in hw_types:
        fw_dir = os.path.join(SCRIPT_DIR, "..", "..", "firmware", hw)
        fw_dir = os.path.abspath(fw_dir)

        if not os.path.isfile(os.path.join(fw_dir, "platformio.ini")):
            print(f"  ✗ ERROR: platformio.ini not found in {fw_dir}")
            sys.exit(1)

        # Build firmware
        print(f"\n  Building firmware ({hw})...")
        result = subprocess.run(
            [pio_cmd, "run"],
            cwd=fw_dir,
            capture_output=False,
            shell=True
        )
        if result.returncode != 0:
            print(f"  ✗ ERROR: Firmware build failed for {hw}")
            sys.exit(1)
        print(f"  ✓ Firmware compiled ({hw})")

        # Filesystem image is only needed for stable browser flasher packages
        if not is_beta:
            print(f"  Building filesystem image ({hw})...")
            result = subprocess.run(
                [pio_cmd, "run", "-t", "buildfs"],
                cwd=fw_dir,
                capture_output=False,
                shell=True
            )
            if result.returncode != 0:
                print(f"  ✗ ERROR: Filesystem build failed for {hw}")
                sys.exit(1)
            print(f"  ✓ Filesystem image built ({hw})")


def copy_artifacts(is_beta=False, beta_version=None):
    """Copies compiled binaries and LittleFS template to docs/flash/."""
    print("\n📋 Copying build artifacts to docs/flash/...")
    print("-" * 40)

    hw_types = ["pcb", "neopixel"]
    littlefs_found = False

    for hw in hw_types:
        print(f"\nProcessing hardware type: {hw}")
        print("-" * 30)

        FIRMWARE_DIR = os.path.join(SCRIPT_DIR, "..", "..", "firmware", hw)
        BUILD_DIR = os.path.join(FIRMWARE_DIR, ".pio", "build", "esp32dev")

        if not os.path.isdir(BUILD_DIR):
            print(f"  ✗ ERROR: Build directory not found: {BUILD_DIR}")
            print(f"    Please run 'pio run' in the firmware/{hw}/ directory first.")
            continue

        if is_beta:
            # Beta releases only output the beta firmware binaries for OTA
            fw_dest_name = "firmware-beta.bin" if hw == "pcb" else "firmware-neo-beta.bin"
            files_to_copy = {
                fw_dest_name: os.path.join(BUILD_DIR, "firmware.bin"),
            }
        else:
            # Stable releases output standard firmware, bootloader, and partitions
            fw_dest_name = "firmware.bin" if hw == "pcb" else "firmware-neo.bin"
            files_to_copy = {
                "bootloader.bin": os.path.join(BUILD_DIR, "bootloader.bin"),
                "partitions.bin": os.path.join(BUILD_DIR, "partitions.bin"),
                fw_dest_name:     os.path.join(BUILD_DIR, "firmware.bin"),
            }

            # Also copy boot_app0.bin (shared tool binary) for initial flashing
            boot_app0_dest = os.path.join(FLASH_DIR, "boot_app0.bin")
            boot_app0_src = os.path.join(FRAMEWORK_DIR, "tools", "partitions", "boot_app0.bin")
            if os.path.isfile(boot_app0_src):
                shutil.copy2(boot_app0_src, boot_app0_dest)
                size_kb = os.path.getsize(boot_app0_dest) / 1024
                print(f"  ✓ boot_app0.bin ({size_kb:.1f} KB)")

        for dest_name, src_path in files_to_copy.items():
            dest_path = os.path.join(FLASH_DIR, dest_name)
            if os.path.isfile(src_path):
                shutil.copy2(src_path, dest_path)
                size_kb = os.path.getsize(dest_path) / 1024
                print(f"  ✓ {dest_name} ({size_kb:.1f} KB)")
            else:
                print(f"  ✗ {dest_name} — source not found: {src_path}")

        if not is_beta:
            littlefs_src = os.path.join(BUILD_DIR, "littlefs.bin")
            littlefs_dest = os.path.join(FLASH_DIR, "littlefs_template.bin")
            if not littlefs_found and os.path.isfile(littlefs_src):
                shutil.copy2(littlefs_src, littlefs_dest)
                size_kb = os.path.getsize(littlefs_dest) / 1024
                print(f"  ✓ littlefs_template.bin ({size_kb:.1f} KB) ← pulled from {hw}")
                littlefs_found = True

    # If building stable and there is no active beta, clean up obsolete beta binaries
    if not is_beta and not beta_version:
        for old_beta in ["firmware-beta.bin", "firmware-neo-beta.bin"]:
            old_path = os.path.join(FLASH_DIR, old_beta)
            if os.path.isfile(old_path):
                try:
                    os.remove(old_path)
                    print(f"  🗑 Removed obsolete {old_beta}")
                except Exception:
                    pass


def main():
    parser = argparse.ArgumentParser(description="Linked Lamp Build & Packaging Tool")
    parser.add_argument("--no-prompt", action="store_true", help="Do not prompt for version, compile with current")
    parser.add_argument("--bump", choices=["major", "minor", "patch"], help="Bump version component")
    parser.add_argument("--beta", action="store_true", help="Make bumped version a beta release")
    parser.add_argument("--promote", action="store_true", help="Promote active beta to stable")
    args = parser.parse_args()

    print("Linked Lamp — Build & Packaging Helper")
    print("=" * 50)

    # Step 1: Manage Versions
    version_info = load_version_info()
    version_info, active_v, is_b, b_num, maj, min_v, pat = manage_versions_interactive(version_info, args)

    print(f"\n📦 Target Firmware Version for this build: v{active_v}")
    print("-" * 50)

    # Save version files
    save_version_info(version_info)
    write_cpp_version_headers(active_v, is_b, b_num, maj, min_v, pat)

    # Step 2: Compile firmware
    print("\n🔨 Step 2: Compiling firmware for PCB and NeoPixel...")
    print("-" * 50)
    compile_firmware(is_beta=is_b)

    # Step 3: Copy build artifacts
    copy_artifacts(is_beta=is_b, beta_version=version_info.get("beta"))

    print("\n" + "=" * 50)
    print(f"Done! Files and binaries are ready in docs/flash/ (v{active_v})")
    print("Stable: " + str(version_info.get("stable")))
    print("Beta:   " + str(version_info.get("beta")))
    print("Commit these files to your repository.")


if __name__ == "__main__":
    main()
